EV_EXIT = 0XFF

EV_KEY = 0X01
EV_MOUSE_MOVE = 0X02
DOWN = 0X01
UP = 0X02

MOUSE_BTN_LEFT = b"\x90"
MOUSE_BTN_RIGHT = b"\x91"
MOUSE_BTN_MIDDLE = b"\x92"

KEY_LEFT_CTRL = b"\xe0"
KEY_LEFT_SHIFT = b"\xe1"
KEY_LEFT_ALT = b"\xe2"
KEY_LEFT_GUI = b"\xe3"
KEY_RIGHT_CTRL = b"\xe4"
KEY_RIGHT_SHIFT = b"\xe5"
KEY_RIGHT_ALT = b"\xe6"
KEY_RIGHT_GUI = b"\xe8"

KEY_A = b"\x04"
KEY_B = b"\x05"
KEY_C = b"\x06"
KEY_D = b"\x07"
KEY_E = b"\x08"
KEY_F = b"\x09"
KEY_G = b"\x0A"
KEY_H = b"\x0B"
KEY_I = b"\x0C"
KEY_J = b"\x0D"
KEY_K = b"\x0E"
KEY_L = b"\x0F"
KEY_M = b"\x10"
KEY_N = b"\x11"
KEY_O = b"\x12"
KEY_P = b"\x13"
KEY_Q = b"\x14"
KEY_R = b"\x15"
KEY_S = b"\x16"
KEY_T = b"\x17"
KEY_U = b"\x18"
KEY_V = b"\x19"
KEY_W = b"\x1A"
KEY_X = b"\x1B"
KEY_Y = b"\x1C"
KEY_Z = b"\x1D"
KEY_1 = b"\x1E"
KEY_2 = b"\x1F"
KEY_3 = b"\x20"
KEY_4 = b"\x21"
KEY_5 = b"\x22"
KEY_6 = b"\x23"
KEY_7 = b"\x24"
KEY_8 = b"\x25"
KEY_9 = b"\x26"
KEY_0 = b"\x27"
KEY_RETURN = b"\x28"
KEY_ENTER = b"\x28"
KEY_ESC = b"\x29"
KEY_ESCAPE = b"\x29"
KEY_BCKSPC = b"\x2A"
KEY_BACKSPACE = b"\x2A"
KEY_TAB = b"\x2B"
KEY_SPACE = b"\x2C"
KEY_MINUS = b"\x2D"
KEY_DASH = b"\x2D"
KEY_EQUALS = b"\x2E"
KEY_EQUAL = b"\x2E"
KEY_LBRACKET = b"\x2F"
KEY_RBRACKET = b"\x30"
KEY_BACKSLASH = b"\x31"
KEY_HASH = b"\x32"
KEY_NUMBER = b"\x32"
KEY_SEMICOLON = b"\x33"
KEY_QUOTE = b"\x34"
KEY_BACKQUOTE = b"\x35"
KEY_TILDE = b"\x35"
KEY_COMMA = b"\x36"
KEY_PERIOD = b"\x37"
KEY_STOP = b"\x37"
KEY_SLASH = b"\x38"
KEY_CAPS_LOCK = b"\x39"
KEY_CAPSLOCK = b"\x39"
KEY_F1 = b"\x3A"
KEY_F2 = b"\x3B"
KEY_F3 = b"\x3C"
KEY_F4 = b"\x3D"
KEY_F5 = b"\x3E"
KEY_F6 = b"\x3F"
KEY_F7 = b"\x40"
KEY_F8 = b"\x41"
KEY_F9 = b"\x42"
KEY_F10 = b"\x43"
KEY_F11 = b"\x44"
KEY_F12 = b"\x45"
KEY_PRINT = b"\x46"
KEY_SCROLL_LOCK = b"\x47"
KEY_SCROLLLOCK = b"\x47"
KEY_PAUSE = b"\x48"
KEY_INSERT = b"\x49"
KEY_HOME = b"\x4A"
KEY_PAGEUP = b"\x4B"
KEY_PGUP = b"\x4B"
KEY_DEL = b"\x4C"
KEY_DELETE = b"\x4C"
KEY_END = b"\x4D"
KEY_PAGEDOWN = b"\x4E"
KEY_PGDOWN = b"\x4E"
KEY_RIGHT = b"\x4F"
KEY_LEFT = b"\x50"
KEY_DOWN = b"\x51"
KEY_UP = b"\x52"
KEY_NUM_LOCK = b"\x53"
KEY_NUMLOCK = b"\x53"
KEY_KP_DIVIDE = b"\x54"
KEY_KP_MULTIPLY = b"\x55"
KEY_KP_MINUS = b"\x56"
KEY_KP_PLUS = b"\x57"
KEY_KP_ENTER = b"\x58"
KEY_KP_RETURN = b"\x58"
KEY_KP_1 = b"\x59"
KEY_KP_2 = b"\x5A"
KEY_KP_3 = b"\x5B"
KEY_KP_4 = b"\x5C"
KEY_KP_5 = b"\x5D"
KEY_KP_6 = b"\x5E"
KEY_KP_7 = b"\x5F"
KEY_KP_8 = b"\x60"
KEY_KP_9 = b"\x61"
KEY_KP_0 = b"\x62"
KEY_KP_PERIOD = b"\x63"
KEY_KP_STOP = b"\x63"
KEY_APPLICATION = b"\x65"
KEY_POWER = b"\x66"
KEY_KP_EQUALS = b"\x67"
KEY_KP_EQUAL = b"\x67"
KEY_F13 = b"\x68"
KEY_F14 = b"\x69"
KEY_F15 = b"\x6A"
KEY_F16 = b"\x6B"
KEY_F17 = b"\x6C"
KEY_F18 = b"\x6D"
KEY_F19 = b"\x6E"
KEY_F20 = b"\x6F"
KEY_F21 = b"\x70"
KEY_F22 = b"\x71"
KEY_F23 = b"\x72"
KEY_F24 = b"\x73"
KEY_EXECUTE = b"\x74"
KEY_HELP = b"\x75"
KEY_MENU = b"\x76"
KEY_SELECT = b"\x77"
KEY_CANCEL = b"\x78"
KEY_REDO = b"\x79"
KEY_UNDO = b"\x7A"
KEY_CUT = b"\x7B"
KEY_COPY = b"\x7C"
KEY_PASTE = b"\x7D"
KEY_FIND = b"\x7E"
KEY_MUTE = b"\x7F"
KEY_VOLUME_UP = b"\x80"
KEY_VOLUME_DOWN = b"\x81"

keyname2scancode = {
    "MOUSE_BTN_LEFT": MOUSE_BTN_LEFT,
    "MOUSE_BTN_RIGHT": MOUSE_BTN_RIGHT,
    "MOUSE_BTN_MIDDLE": MOUSE_BTN_MIDDLE,

    "KEY_LEFT_CTRL": KEY_LEFT_CTRL,
    "KEY_LEFT_SHIFT": KEY_LEFT_SHIFT,
    "KEY_LEFT_ALT": KEY_LEFT_ALT,
    "KEY_LEFT_GUI": KEY_LEFT_GUI,
    "KEY_RIGHT_CTRL": KEY_RIGHT_CTRL,
    "KEY_RIGHT_SHIFT": KEY_RIGHT_SHIFT,
    "KEY_RIGHT_ALT": KEY_RIGHT_ALT,
    "KEY_RIGHT_GUI": KEY_RIGHT_GUI,

    "KEY_A": KEY_A,
    "KEY_B": KEY_B,
    "KEY_C": KEY_C,
    "KEY_D": KEY_D,
    "KEY_E": KEY_E,
    "KEY_F": KEY_F,
    "KEY_G": KEY_G,
    "KEY_H": KEY_H,
    "KEY_I": KEY_I,
    "KEY_J": KEY_J,
    "KEY_K": KEY_K,
    "KEY_L": KEY_L,
    "KEY_M": KEY_M,
    "KEY_N": KEY_N,
    "KEY_O": KEY_O,
    "KEY_P": KEY_P,
    "KEY_Q": KEY_Q,
    "KEY_R": KEY_R,
    "KEY_S": KEY_S,
    "KEY_T": KEY_T,
    "KEY_U": KEY_U,
    "KEY_V": KEY_V,
    "KEY_W": KEY_W,
    "KEY_X": KEY_X,
    "KEY_Y": KEY_Y,
    "KEY_Z": KEY_Z,
    "KEY_1": KEY_1,
    "KEY_2": KEY_2,
    "KEY_3": KEY_3,
    "KEY_4": KEY_4,
    "KEY_5": KEY_5,
    "KEY_6": KEY_6,
    "KEY_7": KEY_7,
    "KEY_8": KEY_8,
    "KEY_9": KEY_9,
    "KEY_0": KEY_0,
    "KEY_RETURN": KEY_RETURN,
    "KEY_ENTER": KEY_ENTER,
    "KEY_ESC": KEY_ESC,
    "KEY_ESCAPE": KEY_ESCAPE,
    "KEY_BCKSPC": KEY_BCKSPC,
    "KEY_BACKSPACE": KEY_BACKSPACE,
    "KEY_TAB": KEY_TAB,
    "KEY_SPACE": KEY_SPACE,
    "KEY_MINUS": KEY_MINUS,
    "KEY_DASH": KEY_DASH,
    "KEY_EQUALS": KEY_EQUALS,
    "KEY_EQUAL": KEY_EQUAL,
    "KEY_LBRACKET": KEY_LBRACKET,
    "KEY_RBRACKET": KEY_RBRACKET,
    "KEY_BACKSLASH": KEY_BACKSLASH,
    "KEY_HASH": KEY_HASH,
    "KEY_NUMBER": KEY_NUMBER,
    "KEY_SEMICOLON": KEY_SEMICOLON,
    "KEY_QUOTE": KEY_QUOTE,
    "KEY_BACKQUOTE": KEY_BACKQUOTE,
    "KEY_TILDE": KEY_TILDE,
    "KEY_COMMA": KEY_COMMA,
    "KEY_PERIOD": KEY_PERIOD,
    "KEY_STOP": KEY_STOP,
    "KEY_SLASH": KEY_SLASH,
    "KEY_CAPS_LOCK": KEY_CAPS_LOCK,
    "KEY_CAPSLOCK": KEY_CAPSLOCK,
    "KEY_F1": KEY_F1,
    "KEY_F2": KEY_F2,
    "KEY_F3": KEY_F3,
    "KEY_F4": KEY_F4,
    "KEY_F5": KEY_F5,
    "KEY_F6": KEY_F6,
    "KEY_F7": KEY_F7,
    "KEY_F8": KEY_F8,
    "KEY_F9": KEY_F9,
    "KEY_F10": KEY_F10,
    "KEY_F11": KEY_F11,
    "KEY_F12": KEY_F12,
    "KEY_PRINT": KEY_PRINT,
    "KEY_SCROLL_LOCK": KEY_SCROLL_LOCK,
    "KEY_SCROLLLOCK": KEY_SCROLLLOCK,
    "KEY_PAUSE": KEY_PAUSE,
    "KEY_INSERT": KEY_INSERT,
    "KEY_HOME": KEY_HOME,
    "KEY_PAGEUP": KEY_PAGEUP,
    "KEY_PGUP": KEY_PGUP,
    "KEY_DEL": KEY_DEL,
    "KEY_DELETE": KEY_DELETE,
    "KEY_END": KEY_END,
    "KEY_PAGEDOWN": KEY_PAGEDOWN,
    "KEY_PGDOWN": KEY_PGDOWN,
    "KEY_RIGHT": KEY_RIGHT,
    "KEY_LEFT": KEY_LEFT,
    "KEY_DOWN": KEY_DOWN,
    "KEY_UP": KEY_UP,
    "KEY_NUM_LOCK": KEY_NUM_LOCK,
    "KEY_NUMLOCK": KEY_NUMLOCK,
    "KEY_KP_DIVIDE": KEY_KP_DIVIDE,
    "KEY_KP_MULTIPLY": KEY_KP_MULTIPLY,
    "KEY_KP_MINUS": KEY_KP_MINUS,
    "KEY_KP_PLUS": KEY_KP_PLUS,
    "KEY_KP_ENTER": KEY_KP_ENTER,
    "KEY_KP_RETURN": KEY_KP_RETURN,
    "KEY_KP_1": KEY_KP_1,
    "KEY_KP_2": KEY_KP_2,
    "KEY_KP_3": KEY_KP_3,
    "KEY_KP_4": KEY_KP_4,
    "KEY_KP_5": KEY_KP_5,
    "KEY_KP_6": KEY_KP_6,
    "KEY_KP_7": KEY_KP_7,
    "KEY_KP_8": KEY_KP_8,
    "KEY_KP_9": KEY_KP_9,
    "KEY_KP_0": KEY_KP_0,
    "KEY_KP_PERIOD": KEY_KP_PERIOD,
    "KEY_KP_STOP": KEY_KP_STOP,
    "KEY_APPLICATION": KEY_APPLICATION,
    "KEY_POWER": KEY_POWER,
    "KEY_KP_EQUALS": KEY_KP_EQUALS,
    "KEY_KP_EQUAL": KEY_KP_EQUAL,
    "KEY_F13": KEY_F13,
    "KEY_F14": KEY_F14,
    "KEY_F15": KEY_F15,
    "KEY_F16": KEY_F16,
    "KEY_F17": KEY_F17,
    "KEY_F18": KEY_F18,
    "KEY_F19": KEY_F19,
    "KEY_F20": KEY_F20,
    "KEY_F21": KEY_F21,
    "KEY_F22": KEY_F22,
    "KEY_F23": KEY_F23,
    "KEY_F24": KEY_F24,
    "KEY_EXECUTE": KEY_EXECUTE,
    "KEY_HELP": KEY_HELP,
    "KEY_MENU": KEY_MENU,
    "KEY_SELECT": KEY_SELECT,
    "KEY_CANCEL": KEY_CANCEL,
    "KEY_REDO": KEY_REDO,
    "KEY_UNDO": KEY_UNDO,
    "KEY_CUT": KEY_CUT,
    "KEY_COPY": KEY_COPY,
    "KEY_PASTE": KEY_PASTE,
    "KEY_FIND": KEY_FIND,
    "KEY_MUTE": KEY_MUTE,
    "KEY_VOLUME_UP": KEY_VOLUME_UP,
    "KEY_VOLUME_DOWN": KEY_VOLUME_DOWN,
}
